name: flutter_guitar_chord
description: Simple and customizable Flutter Guitar Chord widget using CustomPainter for guitar chord diagrams.
version: 0.1.0
homepage: https://github.com/kyawnyeinphyo/flutter_guitar_chord
repository: https://github.com/kyawnyeinphyo/flutter_guitar_chord
issue_tracker: https://github.com/kyawnyeinphyo/flutter_guitar_chord/issues

topics:
  - guitar
  - chords
  - music
  - widgets

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

