name: flutter_guitar_chord
description: Simple and easy to use Flutter Guitar Chord widget using custom painter for guitar chord application
version: 0.0.2
homepage: https://github.com/ygnCybernoob/flutter_guitar_chord

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
